### ISSUE TITLE
GraphError has no code and message

### ISSUE THREAD

**Issue by borys-kupar** [microsoftgraph/msgraph-sdk-javascript#171]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description

When GraphError is constructed in [constructErrorFromRawResponse](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/src/GraphErrorHandler.ts#L49) function it has only raw body set. That seems to be done on intention, but it's not clear what is the reason behind it. 

**Console Errors:** 
```
GraphError {
[1]   statusCode: 400,
[1]   code: null,
[1]   message: null,
[1]   requestId: null,
[1]   date: 2019-05-06T15:13:45.528Z,
[1]   body:
[1]    '{\r\n  "error": {\r\n    "code": "ErrorInvalidIdMalformed",\r\n    "message": "Id is malformed.",\r\n    "innerError": {\r\n      "request-id": "27cf99dc-8493-4fc0-9471-xxxxx",\r\n      "date": "2019-05-06T15:13:45"\r\n    }\r\n  }\r\n}' }
```

## Steps to Reproduce

1. Fetch /users/${userId}/calendars/${calendarId}/calendarView endpoint with malformed calendar id.

**Expected behavior:** 
GraphError should have raw error parsed, and have properties `code`, `message`, `requestId` set.

**Actual behavior:** [What actually happened]
Only raw error is available, other properties are set to `null`.

**Comment by muthurathinam** [comment]
@borys-kupar Thank you for reporting this issue. will fix this in our next release.

**Comment by muthurathinam** [comment]
The fix is released as a preview - [1.7.0-Preview.2](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/1.7.0-Preview.2)

**Comment by borys-kupar** [comment]
Unfortunately the issue seems to be not fixed. The GraphError is constructed in last [else](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/master/src/GraphErrorHandler.ts#L95) block containing the `statusCode` only. The rest of raw error is still not parsed. 

The error I get:
```
GraphError {
   statusCode: 400,
   code: null,
   message: null,
   requestId: null,
   date: 2019-05-29T13:34:45.639Z,
   body:
    '{\r\n  "error": {\r\n    "code": "ErrorInvalidParameter",\r\n    "message": "The value \'2019-06-07T00:00:00.000 00:00\' of parameter \'StartDateTime\' is invalid.",\r\n    "innerError": {\r\n      "request-id": "xxx",\r\n      "date": "2019-05-29T13:34:45"\r\n    }\r\n  }\r\n}' }
```

**Comment by muthurathinam** [comment]
@borys-kupar It is working fine for me. As the error object contains `error` property, [this if](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/master/src/GraphErrorHandler.ts#L90) statement should be true and it should call `constructErrorFromResponse` to get the error response.

This is what I am getting when I try with the same value for startTime as yours while creating a calender event,
```json
{  
   "statusCode":400,
   "code":"InvalidDateTime",
   "message":"The value '2019-06-07T00:00:00.000 00:00' of parameter 'DateTime' is invalid.",
   "requestId":"de7250b7-397a-42f7-a56a-727730787ebe",
   "date":"2019-05-30T00:25:03.000Z",
   "body":"{\"code\":\"InvalidDateTime\",\"message\":\"The value '2019-06-07T00:00:00.000 00:00' of parameter 'DateTime' is invalid.\",\"innerError\":{\"request-id\":\"de7250b7-397a-42f7-a56a-727730787ebe\",\"date\":\"2019-05-30T05:55:03\"}}"
}
```

FYI: I am using version 1.7.0 of the library

**Comment by borys-kupar** [comment]
I use the latest version 1.7.0. It seems like for me error object doesn't contain `error` property so it falls into the last [else statement](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/master/src/GraphErrorHandler.ts#L95).

**Comment by muthurathinam** [comment]
Can you help me with the exact response that you are getting from the library ? Graph error in [this](https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/171#issuecomment-496942015) comment seems to have "error" property in it.

**Comment by borys-kupar** [comment]
@muthurathinam sorry, it seems indeed like I had cached node_module in my Docker container. Can't reproduce the issue anymore.

**Comment by casz** [comment]
I am also seeing a similar issue on 1.7.0. Reverted to 1.6.0, experienced the same after reverting after some debugging: The issue seems to be that Request is not defined
![image](https://user-images.githubusercontent.com/1661688/62860074-5a596080-bcff-11e9-8fc6-31fb2bc45288.png)

Getting a GraphError -1 
```
GraphError {
  statusCode: -1,
  code: null,
  message: null,
  requestId: null,
  date: 2019-08-12T09:55:48.040Z,
  body: null
}
```

**Comment by casz** [comment]
I found the issue related to switching from Node 10 to 12 😓
I see that #197 is released in a preview.
