### ISSUE TITLE
Error TS2307: Cannot find module '@microsoft/microsoft-graph-client'

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-javascript#61]
https://stackoverflow.com/questions/48380812/error-ts2307-cannot-find-module-microsoft-microsoft-graph-client

Error TS2307: Cannot find module '@microsoft/microsoft-graph-client'.
The same happens, when trying to import @microsoft/microsoft-graph-types. Oddly, VS Code resolves the path to the module correctly, but gulp throws the above mentioned error while building.

2123487

**Comment by lumayara** [comment]
I am getting the same error.

**Comment by MIchaelMainer** [comment]
@lumayara I'm sorry that I haven't gotten to this.

**Comment by sibelius** [comment]
this is fixed, can we close?

**Comment by sibelius** [comment]
related to this https://github.com/microsoftgraph/msgraph-typescript-typings/issues/24

**Comment by muthurathinam** [comment]
@lumayara I cannot reproduce this error are you still getting this ? If so can you please provide me the steps to reproduce ?
FYI: I am using the latest version of the microsoft/microsoft-graph-client.

**Comment by muthurathinam** [comment]
User reported this is fixed. Hence closing.!

**Comment by rogercodes1** [comment]
Still seeing this error on 1.7.0 and 2.0.0
What information do you need from me?
